name: Rebuild docker image

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger image rebuild via POST
        run: curl -X POST ${{ DOCKER_TRIGGER_ENDPOINT }}
