name: Rebuild docker image

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger image rebuild via curl POST
        uses: TobiasOlofsson88/github-action-validate-json-request-result@v1.0.5
        with:
          request-method: "POST"
          request-url: ${{ secrets.DOCKER_TRIGGER_ENDPOINT }}
          validate-json: '{ "state": "Success"}'
