name: Rebuild docker image

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger image rebuild via POST
        
        run: curl -X POST ${{ secrets.DOCKER_TRIGGER_ENDPOINT }} | python -c "import sys, json; sys.exit(0 if json.load(sys.stdin)['state'].lower() == 'success' else 1)"
